CREATE TABLE SAEUTILISATEURS (
	LOGIN VARCHAR(50),
	MOTDEPASSE VARCHAR(100),
	EMAIL VARCHAR(100),
	PRIMARY KEY (LOGIN)
);

CREATE TABLE SAEVOTES (
	IDVOTE INTEGER,
	INTITULE VARCHAR(100) NOT NULL,
	OPTION1 VARCHAR(100) NOT NULL,
	OPTION2 VARCHAR(100) NOT NULL,
	RESULTAT INTEGER,
	URNE_U VARCHAR(750),
	URNE_V VARCHAR(750),
	NBBULLETINS INTEGER,
	DATEFIN DATE,
	HEUREFIN INTEGER,
	CONSTRAINT SAEVOTES_PK PRIMARY KEY (IDVOTE)
);

CREATE TABLE SAEVOTER (
	LOGIN VARCHAR(50),
	IDVOTE INTEGER,
	PRIMARY KEY (LOGIN, IDVOTE),
	CONSTRAINT FK_SAEUtilisateurs FOREIGN KEY (LOGIN) REFERENCES SAEUTILISATEURS (LOGIN) ,
	CONSTRAINT FK_SAEVotes FOREIGN KEY (IDVOTE) REFERENCES SAEVOTES (IDVOTE) 
);

CREATE TABLE SAEPASSWORD (
	ID INTEGER,
	PASSWORD VARCHAR(256)
);

INSERT INTO SAEPASSWORD(ID, PASSWORD) VALUES (1, '');

INSERT INTO
	SAEUTILISATEURS (LOGIN, MOTDEPASSE, EMAIL)
VALUES
	(
		'Chirouze',
		'$2a$10$77xE4GyaTQd0OlibvYDNie7hfn6sjAQiJZB5XOl.Pu2g4k7LChwve',
		'chirouze@yopmail.com'
	),
	(
		'capy',
		'$2a$10$pPtKLWwor1G9nJ.dJw1RselXafrEWp7oEx6WpOfYtFnqlHATBBCKG',
		'capybarasae@yopmail.com'
	),
	(
		't',
		'$2a$10$ht8kgD4BT9zTXBakJyWxrOx7xJeXR4ZiU0AN5E0TxnqLGGQhK9oPy',
		'verifutilisateursae@yopmail.com'
	),
	(
		'testeur',
		'$2a$10$UBfByuw6B7OC3FF1Tvfwn.WvOEaJZizXn.AJpV4YIUKF9mS1c1M8G',
		'saeutilisateur@gmail.com'
	),
	(
		'a',
		'$2a$10$ZPRFutejJjYaLHc8g6Y3Lev24U8qwKA/.xkQPWKsBnxbCizjLF4MG',
		's.jocelin@pm.me'
	),
	(
		'car',
		'$2a$10$p9/xM/2LBslHqdbwxKPEtuFzQ17ZphV.WFUzTSnb0em1a2JiESWpG',
		'caracalsae@yopmail.com'
	);



